version: "3.8"
services:
  backend:
    build: ./server
    ports:
      - "5001:5001"
    network_mode: "host"
    environment:
      DB_NAME: test
      DB_USER: postgres
      DB_PASSWORD: qwert@123
      DB_HOST: host
    container_name: server
  frontend:
    build: ./client
    ports:
      - "3000:3000"
    depends_on:
      - backend
    container_name: client
